name: pnpmi
description: "Default pnpm create action"

inputs:
  branch:
    description: "Branch to test"
    required: false

runs:
  using: "composite"

  steps:
    - name: "Install node"
      uses: chlbri/node-github-actions/.github/actions/setup-pnpm@main

    - name: Cache and install dependencies
      uses: chlbri/node-github-actions/.github/actions/cache-store@main
