name: tag & realease
description: "Cache and retrieve cache"

inputs:
  tag:
    description: "Tag string"
    required: true
  token:
    description: "GitHub token with write permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Release
      id: create_release
      uses: chlbri/release-and-tag@latest
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
      with:
        tag_name: ${{ inputs.tag }}
        release_name: Release ${{ inputs.tag }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
