name: pnpm-cache
description: "Cache and retrieve cache"

inputs:
  tag:
    description: "Tag string"
    required: true
  token:
    description: "GitHub token with write permissions"
    required: true

runs:
  using: "composite"
  steps:
    - name: GitHub Tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.token }}
        tag_prefix: "v"
        custom_tag: ${{ inputs.tag }}
