name: Publish

on:
  workflow_call:
    inputs:
      type:
        description: "Type of publish. Can be 'latest' or 'beta', 'next' or 'canary'."
        required: false
        type: string
        default: "latest"
      package:
        description: "The path of the package to publish"
        type: string
        required: false

    secrets:
      NPM_TOKEN:
        description: "NPM token with publish permissions"
        required: false

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write
  packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pnpm repo
        uses: chlbri/node-github-actions/.github/actions/pnpmi@main

      - name: Build
        run: pnpm run build

      - uses: chlbri/pnpm-publish@main
        id: publish
        name: Publish
        with:
          access: public
          filter: ${{ inputs.package }}
          tag: ${{ inputs.type }}
          provenance: true

      - name: Check - updated
        if: ${{ steps.publish.outputs.released }}
        run: echo "${{ steps.publish.outputs.name }} Version changed from ${{ steps.publish.outputs.old-version }} to ${{ steps.publish.outputs.new-version }}"

      - name: Check - not updated
        if: ${{ ! steps.publish.outputs.released }}
        run: echo "Remain the same! - ${{ steps.publish.outputs.old-version }}"

      - name: GitHub Tag
        if: ${{ steps.publish.outputs.released }}
        uses: chlbri/node-github-actions/.github/actions/tag@main
        with:
          tag: ${{ steps.publish.outputs.new-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
